version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
    groups:
      actions-deps:
        patterns: [ "*" ]
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 99
    groups:
      maven-deps:
        patterns: [ "*" ]
  - package-ecosystem: bundler
    directories:
      - "/"
    schedule:
      interval: weekly
      day: friday
    allow:
      - dependency-type: all
    groups:
      ruby-deps:
        patterns: [ "*" ]
  - package-ecosystem: bundler
    directories:
      - "gemfiles/"
    schedule:
      interval: weekly
      day: friday
    allow:
      - dependency-type: all
    groups:
      appraisal-deps:
        update-types: patch
        patterns: [ "*" ]
